pipeline {
    agent any

//     parameters {
//         choice(name: 'PROFILE', choices: ['smoke', 'regression'], description: "Select the maven profile to be executed")
// //        string(name: 'TAG', defaultValue: "AddPlace", description: 'Enter the tag you want to use for execution')
//     }

    stages {
        stage('GIT Checkout') {
            steps {
                echo "*********Git checkout code*********"
                git branch: 'master',
                        credentialsId: 'GitHub_643',
                        url: 'https://github.com/vdinuu/selenium_python.git'
            }
        }
        stage('Setup Python environment'){
            steps {
                bat '''
                python -m venv venv
                venv\\Scripts\\activate
                python.exe -m pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }
        stage('Execute test cases') {
            steps {
                echo "*********Executing test cases**********"
                bat """
                    pytest -s --alluredir=./allure-results
                    """
            }
        }
        }
        post {
            always {
                // Publish the Allure report
                allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
            }
        }
}