pipeline {
    agent any

    parameters {
        choice(name: 'BrowserName', choices: ['chrome', 'firefox', 'edge'], description: "Choose the browser for execution")
    }

    stages {
        stage('GIT Checkout') {
            steps {
                echo "*********Git checkout code*********"
                git branch: 'master',
                        credentialsId: 'GitHub_643',
                        url: 'https://github.com/vdinuu/selenium_python.git'
            }
        }
        stage('Setup Python environment'){
            steps {
                bat '''
                python -m venv venv
                venv\\Scripts\\activate
                python.exe -m pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }
        stage('Execute test cases') {
            steps {
                echo "*********Executing test cases**********"
                bat """
                    pytest -s --browser_name ${params.BrowserName} --alluredir=./allure-results -v --junitxml=result.xml
                    """
            }
        }
        }
        post {
            always {
                // Publish the Allure report
                allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
                junit 'report.xml'
            }
        }
}